prometheus_scrape_jobs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: 'aws'
    ec2_sd_configs:
      - access_key: { get_input: aws_access_key_id }
        secret_key: { get_input: aws_secret_access_key }
        region: { get_input: aws_region_name }
        port: 9100
    relabel_configs:
      - regex: ([^:]+)(?::\d+)?
        replacement: $1:9100
        source_labels:
        - __meta_ec2_public_ip
        target_label: instance
      - source_labels:
        - instance
        target_label: __address__
